### ISSUE TITLE
Recreate group in the target course and enrol users in group doesn't work

### ISSUE THREAD

**Issue by demontech** [Wunderbyte-GmbH/moodle-mod_booking#116]
Hi David,

The option to "Recreate group in the target course and enrol users in group" doesn't work. This is happening on the last version of booking also I tested with M3.3, 3.4, and 3.5. This used to work fine before in previous versions, and yes it is selected in "Automatically enrol users" and "Automatically enrol users in group" in the booking settings.

![image](https://user-images.githubusercontent.com/8148238/44494504-e111bb00-a620-11e8-9d76-adbcf2076ec6.png)

Thank you in advance for taking care of this!

**Comment by atlet** [comment]
David, this is fixed in my repository.

**Comment by dasistwas** [comment]
Hi, OK I will merge.

**Comment by dasistwas** [comment]
@atlet  Your latest commit says "Unfinished work" so I think it is not yet ready for being released..

**Comment by atlet** [comment]
Yes, you are right. I'm working on mobile integration and it's not finished jet. Better to wait.

**Comment by gemguardian** [comment]
hi, 
Ever since the latest updates this option does not work anymore. And alot of issues start to appear that groups in Moodle do not reflect the actually booking. I would be really happy if this could be fixed on short notice. 

Thank you 

Gemma

(moodle 3.5.1 > booking 3.6 Audrey Horne - 2018103100)

**Comment by dasistwas** [comment]
This issue is now fixed in aed633111722089fd79b235f8429c098010d3d57 
This was quite a lot of work. The overall implementation had to be altered. Now groups will be automatically created if they have been deleted in the target course, there is no dialogue anymore when updating the booking option. Otherwise a user who does do a booking after the group was deleted, but before the booking option was updated again would see an error. 
When a booking option name is changed after upon update, the group name in the target course won't change and users will be enrolled to the group with the original name of the booking option.
If anyone could do some testing before releasing the new version on moodle.org, that would be great.
