### ISSUE TITLE
Payment Gateway code causes error on Moodle 3.9

### ISSUE THREAD

**Issue by bradpasley** [Wunderbyte-GmbH/moodle-mod_booking#195]
I'm getting an error due to "Payment Gateway" related code. This feature doesn't exist in Moodle 3.9. Introduced from Moodle 3.10 (https://docs.moodle.org/310/en/Payment_gateways).
Could you please refactor to check this, or make a separate branch for 3.9?

Error output:
```
Exception - Class 'core_payment\helper' not found

[More information about this error](https://docs.moodle.org/39/en/error/moodle/generalexceptionmessage)
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 355 of /mod/booking/classes/price.php: Error thrown
    line 116 of /mod/booking/settings.php: call to mod_booking\price::get_possible_currencies()
    line 89 of /lib/classes/plugininfo/mod.php: call to include()
    line 47 of /admin/settings/plugins.php: call to core\plugininfo\mod->load_settings()
    line 8672 of /lib/adminlib.php: call to require()
    line 26 of /admin/search.php: call to admin_get_root()
```

**Comment by dasistwas** [comment]
@bradpasley Whicht booking version are you using? If you downloaded it from github you might have taken the wrong branch.

**Comment by bradpasley** [comment]
@dasistwas The main branch, latest commit. Is there a separate branch for Moodle 3.9?

**Comment by dasistwas** [comment]
The version.php in the main branch is not correct. That's only for M4 and newer. (But gateways are in Moodle since 3.10). The latest version for 3.9 is available on moodle.org. https://moodle.org/plugins/mod_booking/versions

Also if you are using the custom field feature in booking: we did remove the custom fields and switched to moodle custom fields, but we had no time yet to write a upgrade script. So in general it would be best to stick with the official releases on moodle.org.

@bernhard-wunderbyte could you update version.php in the main branch to only support M4 and newer?
