### ISSUE TITLE
Cannot add user to session if not already enrolled to course

### ISSUE THREAD

**Issue by monsieurmonsieur** [Wunderbyte-GmbH/moodle-mod_booking#253]
**Describe the bug**
When adding users to a session, we used to be able to add any user, regardless of their participation status in the course. Now we must first add users as participants of the course, before being able to add them in a booking session. 
I checked the permission : mod/booking:subscribeusers, but it is set to "Yes".

**Versions uses**
Moodle version: 3.9.16
Boooking version: v7.0.22.02

**To Reproduce**
1. Go to 'a booking page'
2. Click on 'the cogwheel icon next to a booking session'
3. click on 'add other users'
4. use the right search field and enter the name of a user
5. If the user is not enrolled in the course, the text 'No user matching "..."' is displayed

**Expected behavior**
before upgrading to booking 7, any user could be searched, whether they were enrolled in the course or not

**Comment by dasistwas** [comment]
Indeed that has always been an issue. There are several possibilities to tackle that problem: For example auto enrol all users to the course. Personally I think a user who is not allowed to view those users in a system context should not be able to enrol them. So we have to ensure the person enrolling other users has the right to see the users. In a course context that can be tricky. 

If you have any suggestens @monsieurmonsieur please share them.

**Comment by dasistwas** [comment]
I think the permission to look for is that one:

`mod/booking:bookforothers`

And this feature is not only controlled by the permission system. There is also a check if I am assigned to that booking option.

**Comment by monsieurmonsieur** [comment]
Hello @dasistwas and thank you for your answer,

I think the permission is "mod/booking:bookforothers". 

I understand the reason for this restriction as you explained, from a teacher point of view, but we use the ability to add any user to a booking session, using an admin role, with all permissions. 

I don't think it comes from a permission issue, but rather a context issue ? And I can't find why the admin role used to be able to add any user with v5 of booking but can't now in v7, unless the user is already a course participant.

I don't know if you can find further explanation that could solve this problem ?
Thanks again for your time,
Best regards,

**Comment by dasistwas** [comment]
@monsieurmonsieur I just talked with the main developer. This is a bug in 7.0.22. Could you try to work with Moodle 4 and booking version 7.8. There this bug should be fixed. In general we do not support Moodle 3.9 anymore (only security issues, otherwise support has to be purchased). So my recommendation would be to upgrade and test with the new booking version.

**Comment by monsieurmonsieur** [comment]
@dasistwas Thank you, when reviewing the mod_booking versions, I suspected something like that. 
I will make the necessary upgrades, thanks again !

**Comment by bernhard-wunderbyte** [comment]
@monsieurmonsieur As it turned out, you were right, this was no bug but actually not possible for different reasons. However, in Booking 8, we have introduced a new setting now (a little button right on the subscribeusers.php page) that can be used by site admins to activate the booking of anyone - even if they are not enrolled into the course.

If you want to try it, you can install Booking 8. Before doing that, you need to upgrade to Moodle 4 and install our new Wunderbyte Table plugin from here:
https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/archive/refs/heads/main.zip

Then you can install Booking 8 from the MOODLE_401_DEV branch:
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/archive/refs/heads/MOODLE_401_DEV.zip
