### ISSUE TITLE
Inserting pictures problem

### ISSUE THREAD

**Issue by PavelK24** [Wunderbyte-GmbH/moodle-mod_booking#264]
**Describe the bug**
Inserting images in the standard way does not work.
The only option to insert an image to be displayed to users is Drag and drop, but this only works in Firefox

**Versions uses**
Moodle version: 4.1.1
Boooking version: 7.8.7

**To Reproduce**
1. Go to booking module settings
2. Click on editor and add picture. (repository, find a file and add, in editor you can see picture right)
3. Save booking settings
4. Picture not shown

**Expected behavior**

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/128681058/227136960-ac44f4b3-23e3-482a-9fa2-bf8ee7560088.png)

**Additional context**
If I add picture Drag and drop in Firefox, picture shown (if I do this one example in Chrome, not working)

**Comment by bernhard-wunderbyte** [comment]
Thanks for reporting this bug. We will soon release Booking 7.8.7.02 where this will be fixed.

**Comment by PavelK24** [comment]
Thanks, in the day of fixing it runs ok.
And I found new issue if insert picture same way and click to button save.
(DnD in FF cant run now)
![obrazek](https://user-images.githubusercontent.com/128681058/229426092-e534b388-3db0-4be9-af04-42d13f848b3c.png)

**Comment by bernhard-wunderbyte** [comment]
This should be fixed in Booking 8 (DEV version). If you want, you can download Booking 8 here:
https://github.com/Wunderbyte-GmbH/moodle-mod_booking/archive/refs/tags/v8.0.6.zip

Please note, that you'll need Wunderbyte Table for Booking 8 to work. You can download it here:
https://github.com/Wunderbyte-GmbH/moodle-local_wunderbyte_table/archive/refs/tags/v1.5.2.zip
