### ISSUE TITLE
CSV import: unexpected behavior on usage of semesters

### ISSUE THREAD

**Issue by semteacher** [Wunderbyte-GmbH/moodle-mod_booking#306]
**Describe the bug**
A. During import of the CSV file with the following date range provided
![image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/d44b9dfe-417d-4781-8cd6-18cfa1edbace)
into the test env with the following semester settings
![image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/bd8b1434-bb9e-49e9-a74f-e773c54d4d3a)
option's sessions' dates have been forced to the older semester:
![image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/74c2b2c5-56a6-460a-ad3b-10a488f00333)
![image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/d361e498-340a-448c-96a5-9d78df1d05dd)

B. During import of the same CSV file into the test env with NO semester settings - no sessions' dates have been created at all,

**Versions uses**
Moodle version: 4.1.
Boooking version: 8.0.30 but previous affected too

**To Reproduce**
1. Import CSV file with expected date's range
[options_coma_new00.csv](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/files/12419840/options_coma_new00.csv)

**Expected behavior**
A1. At least corresponded range of custom dates have to be created. 
A2. Does a new semestr could be auto-identified?
A3. Does usage of the semester whose tine interval is completely in the past is correct at all? It has no sense for me.
B. Corresponded range of custom dates have to be created

**Comment by bernhard-wunderbyte** [comment]
I think some things are not clear here:

The semester has to be set within a booking instance before the import - this has been fixed with commit e0cfd96f99a13a2d4e746756bdd6cecafb97245c. Now if you import, this semester will be used to generate the optiondate series using the "dayofweektime" string.

If sessions are generated the option's coursestarttime will always be set to the beginning of the first optiondate, the courseendtime will always be the end of the last optiondate (this is done with the function booking_updatestartenddate).

bookingopeningtime and bookingclosingtime should not be confused with coursestarttime and courseendtime. They are used for the availability condition's opening and closing dates. So an option can only be booked from the bookingopeningtime until the bookingclosingtime - but it has nothing to do with the actual beginning (coursestarttime) and end (courseendtime) of the booking option.

We already tested the optiondate series with the client who requested it, and they are happy with it - so we can leave this for now.

However in the future, we'll probably get rid of coursestarttime and courseendtime and store ALL dates as optiondates.

**Comment by bernhard-wunderbyte** [comment]
For the new importer requested in issue #310 we'll need to make sure that optiondate series generation works properly for updating existing options too. (So old sessions will be deleted before creating new ones.)

**Comment by semteacher** [comment]
@bernhard-wunderbyte  Thank you for explanation. Booking availability conditions have been created as per specification.
Despite of this - I still have doubts. Check my post again - because semester with time in the past was configured to be used in booking - all dates had been created in the past, where availability was set-up correctly (as per csv). But final arrangement does not make sense for me (useless combination) . How about at least warning on date series creatnion - that current semestr already in the past ?

**Comment by bernhard-wunderbyte** [comment]
Yes, we could show a warning if a semester is used that is already in the past, that is actually a good idea. I created issue #311 for this.
