### ISSUE TITLE
Check Course enrollment and Group enrolement

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-mod_booking#384]

**Comment by bernhard-wunderbyte** [comment]
@georgmaisser:
In "Booking instance settings" > "Advanced options" there are these two settings:

- Automatically enrol users
- Automatically enrol users in group

Both work as expected. If a user books (or is subscribed by another user), (s)he is also enrolled into the course.
If the group setting is turned on, he'll also get added to a group named with this schema: "instancename - optionname-without-prefix (optionid)"

=> We should probably add the titleprefix to the group name here. Instead of the optionid, we could also use the unique option identifier.

The task to enrol users at course start and not immediately has been removed in the new option form interface. Do we need to restore it?

I'll close this ticket for now and will create a new issue for a new adhoc task that runs when the course starts. So a user gets enrolled only at course start (instead of immediately).
