### ISSUE TITLE
Behat test for new feature cancel bought item

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-mod_booking#454]
A bought item can now be canceled not only via shopping cart history, but directly from booking.

Please write a behat test for this feature:

https://github.com/Wunderbyte-GmbH/moodle-mod_booking/pull/453

The differences in the modal come from the different quota consumed logic set in the booking options.

https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/7524621/b52f8710-2b5a-4d2d-8021-ddbea017c912

**Comment by semteacher** [comment]
Have installed dev_401 branches of shopping_cart, bookinf and wb_table. No modal, cancellation not processed. No errors.


![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/c2c8f46b-cdab-48c7-a1ef-37f054b88930)

Colud it be the problem that dates are in the past? But I was allowed to book (as admin)

**Comment by semteacher** [comment]
1. Above solved by editing each booking option - too old DB with no json data for booking option. 
Hovewer, this could indicate a potential issues with continuous upgrading process (eligible json value had to be created at some particular step when new features were introduced)
2. How purcase could be made if no shopping_cart installed? It not mandatory and not listed to install for tests at GitHub

**Comment by semteacher** [comment]
When price is present but shopping cart not booking is impossible. This is case for tests at github now (no shopping cart dependency has bee nadded yet)
I made override to book user directly in code. It works but cancellation still impossibele

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/81554afc-53ee-431b-86d5-350b201bae86)

definitely because "cancel modal" has been provided from shoppingcart

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/8b4e353d-ab83-4349-af73-0e740d838900)

Solutions:
1. To have behat test which will work only locally where shoppig_cart installed (under development)
2. Add shoppig_cart dependency to the github workflow file (expected more time for tests to be passed at github)

**Comment by semteacher** [comment]
It looks like that to complete behat test - no other way than have shopping_cart installed. Even if I override and instantiate booking answer via DB - at least "shopping_cart histiry" table required.... 

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/e3a87ab3-897a-4db5-b6ae-755779edf58d)

If shopping cart not being installed - "cancelmyself" not applied at all

![Image](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/assets/1571998/8c31b7ec-0fd2-4650-a59b-104e6d7ba952)

**Comment by semteacher** [comment]
@georgmaisser  Task is complete except
"The differences in the modal come from the different quota consumed logic set in the booking options."
Sorry cannot exactly takes differences (even with video). What settings and where have to be customized?
