### ISSUE TITLE
Cannot save a Booking

### ISSUE THREAD

**Issue by daledavies** [Wunderbyte-GmbH/moodle-mod_booking#55]
When setting up a new booking, after clicking on either of the Save buttons, I am redirected back to /course/modedit.php like as if I have not filled out one of the mandatory fields.

Using latest version of booking module (2016071202) and Moodle (20160804), hosted on a LAMP stack.

**Comment by dasistwas** [comment]
@daledavies I can not reproduce this. Could you please elaborate: Which settings did you use and add some screenshots or even better a screencast. Thank you.

**Comment by daledavies** [comment]
@dasistwas Here you go, I left debugging on at the start so you can see error output...

http://screencast-o-matic.com/watch/cDjQlkiKuE

**Comment by dasistwas** [comment]
@daledavies Thank you for that screencast. Very strange. I do not have this behaviour on my testing machines. Could you elaborate about the system you are using? MySQL, Apache2, which php version. You will find that searching for phpinfo in the admin block. Could you also disable debugging completely in the debug settings (The first dropdown menu in the debug settings, instead of just removing the checkbox option) and try again?

**Comment by daledavies** [comment]
Phew, after some frantic testing I've discovered that it is failing on the booking manager name being invalid, the error message for this was not showing on our theme. 

Is id possible to preset this, to a username which does exist such as the person who is setting up the activity? There is no "admin" username.

**Comment by dasistwas** [comment]
That's a good idea. Will try.

**Comment by dasistwas** [comment]
Fixed in f3ca970343a258ce5f62c6607662b5b40c9ae8fa and released at https://moodle.org/plugins/mod_booking
