### ISSUE TITLE
Testing advanced rules

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-mod_booking#592]
We added a new feature to the rules:
- one rule allows to skip the execution of another rule or rules

![Screenshot 2024-07-30 at 10 51 15](https://github.com/user-attachments/assets/2f65dd11-2987-4254-8816-988484dc1e94)

In the example when the rule "Overrule rule" applies, the two other rules "Änderungen in Buchungsoption" & "Bookinganswer cancelled" will not be executed. 
If an event only causes "Bookinganswer cancelled" and not "Overrule rule", actions from "Bookinganswer cancelled" should of course still be executed.
The (1) after the name of the rule is the id of the instance, these are all global rules, but since there can also be specific rules for bookinginstances we added this integer.

Could you please extend the rules tests to see if this works as expected?

- [x] behat test
- [x] phpunittest

**Comment by semteacher** [comment]
Have created a Behat test which is working OK.
Tried to create phpunit but faced issue when each next test on booking _rules preserve rule form at least 1st test. See https://github.com/Wunderbyte-GmbH/moodle-mod_booking/commit/b84c7b185313abdbe4b6aea934fc13a453d4e838 for code details.
Debugging: 
- test_rule_on_rule_override() placed as 1st in file, list of rules and message looks OK
![image](https://github.com/user-attachments/assets/a6444a10-eccb-4622-807e-7cc082916c75)
- test_rule_on_rule_override() placed as last. List of rules and message being taken from the 1st test in file - test_rule_on_booking_option_update() And it happens despite` $this->resetAfterTest(true); `had been enforced (!)
Moreover - I have even tried to delete rule explicitly `rules_info::delete_rule($rule1->id); `but it does not help either. 
![image](https://github.com/user-attachments/assets/b5b60721-8e55-406f-8284-e339226ce4cc)

I faced same behavior few times already and still not fully resolve it. It might be caused by wrong approach I crated phpunit tests at all - because I am strugling of following recommendation
![image](https://github.com/user-attachments/assets/dc0a33d8-a791-4e96-965e-18d8ee761abd)
However, enforcing object's mock with combination of onlyMethods / willReturn does not have a lot of sense to me in current circumstances. So I need an assistance / adwise on this

**Comment by semteacher** [comment]
Have to express an issue which could indicate a ptoential problems with rules.
Faced it specifically under phpunit tests there https://github.com/Wunderbyte-GmbH/moodle-mod_booking/commit/b84c7b185313abdbe4b6aea934fc13a453d4e838#diff-f44f9514b3b71a68fa866cb953211675c982946b3f7837dc2d2dd1c4ee995aa2
The rule had created in the 1st test in file - persists through all tests in the same file... 
And It cannot be deleted 
`$this->resetAfterTest(); `
does not destroy that rule(s).
even explicit calling of `rules_info::delete_rule($rule1->id); `also do not destroy it
What I found is the static variable under booking_rules class
`public static $rules = [];`
which persist during execution time. Does it had been used for caching purpose?
But even forcing it to the empty array in test does not resolve the above issue.
I am wonder if it could affect normal workflow.

**Comment by semteacher** [comment]
Finally I found one more class-level static variable. Reseting both after each test seems solved an issue (https://github.com/Wunderbyte-GmbH/moodle-mod_booking/commit/295725dc5d0d7ba182af6d4428a89bc80027605e):
```
rules_info::$rulestoexecute = [];
booking_rules::$rules = [];
```
