### ISSUE TITLE
TEST: Save entities in bookingoption form

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-mod_booking#593]
In a bookingoptionform, if plugin entities is installed and entitites are given, it should be possible to save to select an entity, save it, see it selected in the bookingoption card and the link should work
![Screenshot 2024-07-30 at 11 07 12](https://github.com/user-attachments/assets/e83f69a3-4473-4c49-981d-2f3c796ffcf7)

![Screenshot 2024-07-30 at 11 07 23](https://github.com/user-attachments/assets/90a341d5-ab68-4f8d-b830-be04ac19ae91)

![Screenshot 2024-07-30 at 11 08 45](https://github.com/user-attachments/assets/04c66a8e-88c8-4384-a810-bf2b808f68ad)

Tests:

- [x] behat
- [x] phpunit

**Comment by semteacher** [comment]
The "entites" local plugin does not included in the list of required plugin for GitHub actions. To create Behat test it has to be included. In case of phpunit - it will be possible to create test which will could be fully executed only locally, in presence of the "entites" plugin . @georgmaisser what is your opinin - should I add "entites" as dependencies to the booking or should I try with phpunit only?

**Comment by eynimeni** [comment]
entities should not be required for booking plugin. but for the actions in github we can require it. if this can not be done seperately, just proceed with phpuni

**Comment by semteacher** [comment]
Behat suports both optiob-level entity and option date-level entity.
Have created a phpunit. It works for optiob-level entity but fails to assign date-level entity. 
What is the correct wat to add it in code? Have tried below but no location for date in option's settings is shown:
```
        $record->optiondateid_1 = "0";
        $record->daystonotify_1 = "0";
        $record->coursestarttime_1 = strtotime('20 June 2050');
        $record->courseendtime_1 = strtotime('20 July 2050');
        $record->er_saverelationsforoptiondates = 1;
        $record->local_entities_entityarea_1 = "optiondate";
        $record->local_entities_entityid_1 = $entityid2; // Option date entity.
```
After some debugging I found:
1. Strange code in the `entities->prepare_save_field()`  which is newer in use because `$option` never instantiated there (and logic looks outdated - it intends to force the same entity all the time)
![image](https://github.com/user-attachments/assets/25627be6-fc0e-4b20-aae9-52d443252992)

2. I need some hints about logic of optiondte->save() because entity id seems like being lost there  
![image](https://github.com/user-attachments/assets/f6ac5ec6-dd7b-422f-bbc5-1bd5e4ee97bd)
- but it happens only during phpunit test.  Value had been preserved for manual or behat as expected...

UPD: found workaround for the phpunit. Option date had been saved but not shown in option's settings up to 
```
$session = reset($settings->sessions);
$entities = $handler->get_instance_data($session->optiondateid); 
```
