### ISSUE TITLE
Write Test for #601

### ISSUE THREAD

**Issue by georgmaisser** [Wunderbyte-GmbH/moodle-mod_booking#604]
#601 
- [x] phpunit test if possible
- [x] behat test if possible

**Comment by semteacher** [comment]
Got an error when tied to create a subbooking item with price
![Image](https://github.com/user-attachments/assets/c9e7fc82-fdf3-4928-ad47-6cf9db937fc8)
```

Invalid course module ID
File: /lib/dml/moodle_database.php
Line: 1658
Stack trace:
SELECT id,course FROM {course_modules} WHERE id IS NULL
[array (
)]
Error code: invalidcoursemodule
* line 1658 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
* line 1634 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
* line 270 of /lib/classes/context/module.php: call to moodle_database->get_record()
* line 690 of /mod/booking/classes/price.php: call to core\context\module::instance()
* line 595 of /mod/booking/classes/price.php: call to mod_booking\price::add_price()
* line 262 of /mod/booking/classes/subbookings/sb_types/subbooking_additionalitem.php: call to mod_booking\price->save_from_form()
* line 183 of /mod/booking/classes/subbookings/subbookings_info.php: call to mod_booking\subbookings\sb_types\subbooking_additionalitem->save_subbooking()
* line 72 of /mod/booking/classes/form/subbookingsform.php: call to mod_booking\subbookings\subbookings_info::save_subbooking()
* line 75 of /lib/form/classes/external/dynamic_form.php: call to mod_booking\form\subbookingsform->process_dynamic_submission()
* line ? of unknownfile: call to core_form\external\dynamic_form::execute()
* line 253 of /lib/external/classes/external_api.php: call to call_user_func_array()
* line 83 of /lib/ajax/service.php: call to core_external\external_api::call_external_function()
```

Notre: same issue has raised in case if you want to add a person as subbooking

Upd: debugging shown that error raised there
![Image](https://github.com/user-attachments/assets/6e8947d8-562c-4a81-99ed-be75fb185c48)
because $itemid contains subbokingID instead of booking optionID. This is actually, correct. But should "option_update" event being called at all for subboking price update?

**Comment by georgmaisser** [comment]
Hi, option update should be called, but obviously we need to get instance of option settings with optionid, not the subbooking item id. can you fix it please! Thanks for finding this bug!

**Comment by semteacher** [comment]
@georgmaisser Have proposed a solution. Works OK with new test... Check if approach is OK, please.
