### ISSUE TITLE
Waiting List Process

### ISSUE THREAD

**Issue by danbuntu** [Wunderbyte-GmbH/moodle-mod_booking#693]
Hello 

Could you please explain the workflow for users on a waiting list?

We have booking that is full and has users on the waiting list.

When we cancel ones of the users on the booking the users on the waiting list receive an email with a status change of 'You are on the waiting list'. They aren't automatically moved on on the now free space. Additionally if an other user then goes to the booking they they are able to booking onto it and so jump the queue.

**Comment by dasistwas** [comment]
@bernhard-wunderbyte could you have a look at that?
@danbuntu could you provide as the version used.

**Comment by danbuntu** [comment]
@dasistwas sure we're using 8.4.7

**Comment by bernhard-wunderbyte** [comment]
@danbuntu Please have a look at you global booking settings under https://<yourURL>/admin/settings.php?section=modsettingbooking

There you'll find a setting called "**Turn off automatic moving up from waiting list after a booking option has started.**" Please make sure that this checkbox is **not checked**.  Please let me know if this solved the issue or if we have to further investigate this.

<img width="400" alt="Bildschirmfoto 2024-11-08 um 09 44 56" src="https://github.com/user-attachments/assets/456249e7-7137-4034-a408-85e7459ba740">

**Comment by danbuntu** [comment]
These are all set to off:

[image: image.png]

**Comment by bernhard-wunderbyte** [comment]
Can you please also check if the booking option has a price set? Currently, the automatic moving up from the waiting list to booked users is not working if a price is set. So within the booking option you have to make sure that the checkbox "Only book with price" is turned off.

**Comment by danbuntu** [comment]
Yes we have that option turned off:

[image: image.png]

**Comment by bernhard-wunderbyte** [comment]
Do you have shopping cart installed (local_shopping_cart)?

**Comment by danbuntu** [comment]
Yes, I have it installed.

**Comment by bernhard-wunderbyte** [comment]
If you do not need it, you can uninstall it and see if it works then. @georgmaisser Can you have a look at this?

**Comment by georgmaisser** [comment]
I just had a look again, and there are exactly three reasons why the syncing of the waitinglist is turned off

- The setting "turnoffwaitinglist" (https:///admin/settings.php?section=modsettingbooking)
- The setting "turnoffwaitinglistaftercoursestart" (https:///admin/settings.php?section=modsettingbooking)
- When prices are used in the booking option. If prices are used and users need to pay, obviously you can't just book the users (because on the waitinglist, they have not paid yet).

When you use prices and the shopping cart, you should notify users on the waitinglist that they can pay. This can be done via the Booking Rules.

Please be aware that when you answer via e-mail, we don't see any pictures you send, so please come on GitHub to send us full information. Thank you!

**Comment by bernhard-wunderbyte** [comment]
I'll close this for now.
