### ISSUE TITLE
Bugfix: Block campaigns with price MUSI-612

### ISSUE THREAD

**Issue by eynimeni** [Wunderbyte-GmbH/moodle-mod_booking#719]
- [x] make sure campaigns containing price are blocked as well by active and applicable campaign

Regarding tests @semteacher 
We need to adjust tests to make sure, that options aren't bookable when there is a price set. 
This is not working yet. I will fix it ASAP. @semteacher you could already start extending the tests (in a separate branch) - as a form of test driven development. I will be able to work on this from tuesday on (soonest)

#689

**Comment by semteacher** [comment]
@eynimeni Could you, please, provide me with some sort of scenario (settings, expected outcome)

**Comment by eynimeni** [comment]
the scenarios as described in https://github.com/Wunderbyte-GmbH/moodle-mod_booking/issues/689
and the bookingoptions have a price set (or multiple prices for price-categories)
it shouldn't be possible to book a bookingoption with price if a campaign is blocking it
(at the moment, it is possible)

**Comment by semteacher** [comment]
For the following:
- students
![image](https://github.com/user-attachments/assets/8efa2d87-6feb-44dc-9fa0-30c9ed80fb3f)
- prices / options / answers
![image](https://github.com/user-attachments/assets/34b74a6a-62ba-413c-8051-00f4b15489a5)
- and for campaing like in the https://github.com/Wunderbyte-GmbH/moodle-mod_booking/issues/689#issuecomment-2472906312
I got the following:
a) student 1
![image](https://github.com/user-attachments/assets/b5ed2287-7034-4dae-a534-74881dd4c749)
(seems correct for me?)
b) students 2 and 3
![image](https://github.com/user-attachments/assets/544b37d1-a0e9-4fc9-a780-4bee23763926)
(seems correct for me?)
Same case with 2nd blocking campaign. It seems to me that blocking has been extended for option with prices already?

**Comment by eynimeni** [comment]
great, thank you!
I thought there was a problem because I tested with capability 'bookforothers' this enables booking (as for other conditions)
maybe you could extend the test for one more person with this capability and make sure, he/she is able to book although campaign is displayed

**Comment by semteacher** [comment]
- [x] I have tried to create a blocking campaign with booking custom field but when user profile field does not defined at all.

Got error
```
Exception - Warning: Undefined property: stdClass::$cpfield in [dirroot]/mod/booking/classes/booking_campaigns/campaigns/campaign_blockbooking.php on line 197
File: /lib/behat/lib.php
Line: 157
Stack trace:
Error code: generalexceptionmessage
* line 157 of /lib/behat/lib.php: Exception thrown
* line 197 of /mod/booking/classes/booking_campaigns/campaigns/campaign_blockbooking.php: call to behat_error_handler()
* line 186 of /mod/booking/classes/booking_campaigns/campaigns_info.php: call to mod_booking\booking_campaigns\campaigns\campaign_blockbooking->save_campaign()
* line 69 of /mod/booking/classes/form/campaignsform.php: call to mod_booking\booking_campaigns\campaigns_info::save_booking_campaign()
* line 75 of /lib/form/classes/external/dynamic_form.php: call to mod_booking\form\campaignsform->process_dynamic_submission()
* line ? of unknownfile: call to core_form\external\dynamic_form::execute()
* line 253 of /lib/external/classes/external_api.php: call to call_user_func_array()
* line 83 of /lib/ajax/service.php: call to core_external\external_api::call_external_function()
```
I think such case should be possible?
UPD: warning fixed but error remains - see comment below:

**Comment by semteacher** [comment]
Recent changes starts affecting options without customfield value has been defined (customfield is empty)
![image](https://github.com/user-attachments/assets/b29f90bb-b2c7-4f5c-ae17-d3349020e118)
![image](https://github.com/user-attachments/assets/596c7b12-d43d-4921-a4fd-2a5cd18483ad)
![image](https://github.com/user-attachments/assets/a8a081ca-04ff-4971-ab00-96163cee6edf)

- campaing require presence of booking customfield and value of profile field shoud doas not match given

{"bofieldname":"bcustom1","fieldvalue":"include","campaignfieldnameoperator":"=","cpfield":"ucustom1","cpoperator":"!~","cpvalue":["student"],"blockoperator":"blockbelow","blockinglabel":"Below50","hascapability":null,"percentageavailableplaces":50}

- it happens because looged-in student profiel field match condition 
![image](https://github.com/user-attachments/assets/9ab59af8-63cc-45ee-8332-c86cfbaeebc4)

- but above is violates the rule
![image](https://github.com/user-attachments/assets/678102e1-55ff-405c-aec8-3cf19a281452)

**Comment by semteacher** [comment]
1st error form https://github.com/Wunderbyte-GmbH/moodle-mod_booking/issues/719#issuecomment-2507547715 being solved

**Comment by semteacher** [comment]
UPD: fixed
- [x] Under Moodle 4.1 / php 7.4 the following exception occurs:

`Exception: Moodle exception: Exception - Argument 3 passed to mod_booking\booking_campaigns\campaigns_info::check_if_campaign_is_active() must be an instance of mod_booking\booking_campaigns\mixed, string given, called in [dirroot]/mod/booking/classes/booking_campaigns/campaigns/campaign_blockbooking.php on line 272`

It caused by unsupported in pjp7.4 usage of "mixed" pseudo-type: https://stackoverflow.com/questions/37199403/how-to-use-mixed-parameter-type-in-my-own-functions

**Comment by semteacher** [comment]
The only remaining issue is https://github.com/Wunderbyte-GmbH/moodle-mod_booking/issues/719#issuecomment-2508281230

**Comment by eynimeni** [comment]
@semteacher we need to extend the behat tests and add a scenario for users that aren't logged in. if there is a shortcode displayed on landing page displaying booking options (I guess you already use this setting somewhere - otherwise let me know), and make sure that campaigns are applied correctly for these users as well (price calculated correctly). we also need this for users logged in as guest. 
Could you please do this? Let me know if something was unclear!

**Comment by eynimeni** [comment]
> The only remaining issue is [#719 (comment)](https://github.com/Wunderbyte-GmbH/moodle-mod_booking/issues/719#issuecomment-2508281230)

Thank you very much for your efforts on this topic, that made it possible for me to find the fix very quickly. (see 2ff11de37df8900fd674586b2469f39b1f1d5dc9)

**Comment by semteacher** [comment]
@eynimeni 
Are the following shortcodes could be used (got it under another issue):
[allekurseliste search=true filter=true sort=true]
[allekursekarten search=true sort=true filter=true]
?
Provide samples if no, please

**Comment by eynimeni** [comment]
> @eynimeni Are the following shortcodes could be used (got it under another issue): [allekurseliste search=true filter=true sort=true] [allekursekarten search=true sort=true filter=true] ? Provide samples if no, please

yes exactly, these are the shortcodes that could be used!
