### ISSUE TITLE
Booking templates from deleted instance handled as active? (Bug plus feature-request)

### ISSUE THREAD

**Issue by VOOM108** [Wunderbyte-GmbH/moodle-mod_booking#764]
**Describe the bug**
We had 5 rules in a test course that were saved as templates, 4 of which were used in a live course and changed from there. I deleted the booking instance in the test-course where the templates came from. This morning, a rule that is only in the db as useastemplate = 1 tried to send 117 mails but failed because of the missing context from the deleted instance. 

After thorough examination of the tables and contents in the database, I decided to delete all rules, remove the templates from the database and create new rules from scratch. This was to address another issue with the additional mails sent after certain changes to a rule have been made. 

I suppose the handling of templates needs to be dealt with differently, not associating them with potentially deleted rules. Also, template management should be possible in the GUI. 

**Versions uses**
Moodle version: [Moodle](http://moodle.org/) [4.4.1 (Build: 20240610)](https://moodledev.io/general/releases)
Booking version: 8.8.1 (2024112500)

**Comment by eynimeni** [comment]
Thank you very much for this feedback. Indeed, if a rule is set as a template, this doesn't mean, it will not be executed. 
We will add a toggle to (de-)activate given rules soon.

**Comment by eynimeni** [comment]
Dear @VOOM108 

with the recent changes, we hope your troubles don't occur anymore
- [x] Rules of instance are deleted on deletion of booking instance
- [x] Rules can be set active or inactive

The first improvement is already deployed in todays release: https://github.com/Wunderbyte-GmbH/moodle-mod_booking/releases/tag/v8.9.1
Whereas the new feature to deactive rules will only be present in the next version of mod_booking

Thank you again for reaching out, we are truly grateful about feedback from the community! Please let us know if you encounter other irregularities.

**Comment by VOOM108** [comment]
This sounds a little like I had partly something else in mind. I was assuming, that the rules of the instance were not deleted, because they were saved as rule-templates. They had the flag useastemplate = 1 in the database. But were executed anyway, even though being templates only. Now probably if deleting the instance where they were saved as templates these get deleted as well, which, in most cases, will not be desirable, because it would remove the templates. 

While it is a good addition, to be able to deactivate rules without deleting them, this would not address the topic of the management of rule-templates. These should be independent of any booking instance and should under no circumstances be executed without being linked to a booking instance. 

My feature suggestion was thus to include some kind of management of templates on a global level. A place where templates are listed and can be edited (and deleted), with the result of the changes being available the next time the template is used to create an active rule based on the template.

At the moment the templates are linked to an instance and only designated as templates by the flag in the database; and with the new update, as it sounds to me, would be deleted with the instance they were saved from as templates.

**Comment by eynimeni** [comment]
Hi,

Yes, you are correct—when an instance is deleted, all rules defined as templates within it are also deleted.
Previously, we didn’t have the concept of rules functioning _only_ as templates, which is why we introduced the active/inactive flag. This allows a rule to be marked as inactive and used purely as a template.

We understand your point about the need for a dedicated template management interface. However, implementing such a feature would require additional development time, and we plan to prioritize this once we have paying customers to support the effort.

In the meantime, the workaround is to either:

1. Use a dedicated instance for templates (without deleting it) and deactivate the relevant rules, or
2. Create templates directly at the global level and mark them as inactive.

If you’re interested in funding the development of this feature or others, we’d be happy to prioritize your requirements. Please let us know if this is something you’d like to explore further.
And thank you again for your feedback!

BTW: I just implemented an overview of the bookingrules in other instances on the global edit_rules.php

**Comment by VOOM108** [comment]
This solution as it is now is fine; as long as one knows that that is the way it is handled, the instance with the templates can be used as a pool for setting up templates. :)
